<a href="https://colab.research.google.com/github/EsraCesur4/MusicEmotionRecognition/blob/main/NaiveBayes_for_Emotion_Recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import torch

# Data

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/Ezeysay16/veridosyalari/main/train_set.csv")
df.head()

,id,name,artist,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,realease_year,emotion_tag
0,1000,Breakeven,The Script,0.630,0.694,10,-4.501,1,0.0242,0.144,0.000000,0.0835,0.490,94.034,261427,4,2008,chill
1,1001,Why Suffer??,Carlos Truly,0.593,0.458,0,-9.108,1,0.0774,0.495,0.059500,0.0878,0.731,168.082,200102,4,2022,NaN
2,1002,Out Here On My Own,Various Artists,0.411,0.129,7,-15.070,1,0.0358,0.980,0.000025,0.0850,0.222,136.215,193360,4,1980,NaN
3,1003,home (feat. Kehina),ones,0.771,0.361,0,-15.171,0,0.0517,0.670,0.826000,0.1080,0.259,105.992,173615,4,2022,NaN
4,1004,Way down We Go,KALEO,0.489,0.505,10,-8.022,0,0.1170,0.579,0.000333,0.1040,0.337,163.255,213707,4,2016,NaN

In [ ]:
columns = ["id","name", "artist","realease_year", "key", "mode", "time_signature", "duration_ms"]
for col in columns:

  del df[col]
df.head()

,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,emotion_tag
0,0.630,0.694,-4.501,0.0242,0.144,0.000000,0.0835,0.490,94.034,chill
1,0.593,0.458,-9.108,0.0774,0.495,0.059500,0.0878,0.731,168.082,NaN
2,0.411,0.129,-15.070,0.0358,0.980,0.000025,0.0850,0.222,136.215,NaN
3,0.771,0.361,-15.171,0.0517,0.670,0.826000,0.1080,0.259,105.992,NaN
4,0.489,0.505,-8.022,0.1170,0.579,0.000333,0.1040,0.337,163.255,NaN

In [ ]:
labelled = df[df["emotion_tag"].notnull()]
labelled.head()

,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,emotion_tag
0,0.630,0.694,-4.501,0.0242,0.144000,0.000000,0.0835,0.490,94.034,chill
8,0.734,0.637,-5.677,0.1410,0.046200,0.000023,0.0602,0.648,169.977,sad
12,0.687,0.792,-4.023,0.0353,0.000802,0.000000,0.2000,0.864,133.962,happy
18,0.696,0.592,-6.281,0.3190,0.152000,0.000000,0.1270,0.232,188.051,angry
19,0.509,0.522,-4.648,0.1890,0.013000,0.000000,0.3290,0.229,132.087,chill

In [ ]:
unlabelled = df[df["emotion_tag"].isnull()]
unlabelled.head()

,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,emotion_tag
1,0.593,0.458,-9.108,0.0774,0.4950,0.059500,0.0878,0.731,168.082,NaN
2,0.411,0.129,-15.070,0.0358,0.9800,0.000025,0.0850,0.222,136.215,NaN
3,0.771,0.361,-15.171,0.0517,0.6700,0.826000,0.1080,0.259,105.992,NaN
4,0.489,0.505,-8.022,0.1170,0.5790,0.000333,0.1040,0.337,163.255,NaN
5,0.769,0.718,-4.039,0.0619,0.0656,0.000000,0.2650,0.757,92.969,NaN

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Creating a instance of label Encoder.
le = LabelEncoder()

# Using .fit_transform function to fit label
# encoder and return encoded label
label = le.fit_transform(labelled['emotion_tag'])

# printing label
label

labelled.drop("emotion_tag", axis=1, inplace=True)

# Appending the array to our dataFrame
# with column name 'Purchased'
labelled["emotion_tag"] = label

# printing Dataframe
labelled

<ipython-input-6-043c6d2e1a2d>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  labelled.drop("emotion_tag", axis=1, inplace=True)
<ipython-input-6-043c6d2e1a2d>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  labelled["emotion_tag"] = label

,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,emotion_tag
0,0.630,0.694,-4.501,0.0242,0.144000,0.000000,0.0835,0.490,94.034,1
8,0.734,0.637,-5.677,0.1410,0.046200,0.000023,0.0602,0.648,169.977,3
12,0.687,0.792,-4.023,0.0353,0.000802,0.000000,0.2000,0.864,133.962,2
18,0.696,0.592,-6.281,0.3190,0.152000,0.000000,0.1270,0.232,188.051,0
19,0.509,0.522,-4.648,0.1890,0.013000,0.000000,0.3290,0.229,132.087,1
...,...,...,...,...,...,...,...,...,...,...
2781,0.656,0.271,-12.363,0.1520,0.497000,0.890000,0.1100,0.354,180.055,1
2782,0.712,0.672,-6.568,0.1650,0.641000,0.000023,0.1120,0.422,127.016,1
2784,0.794,0.686,-3.566,0.2050,0.086500,0.000000,0.0656,0.759,98.050,2
2788,0.507,0.860,-6.785,0.1150,0.019900,0.038700,0.2510,0.557,79.793,0
2799,0.750,0.277,-10.054,0.2990,0.771000,0.920000,0.1170,0.922,170.061,1

In [ ]:
test = pd.read_csv("https://raw.githubusercontent.com/Ezeysay16/veridosyalari/main/test_set_no_labels.csv")
test.head()

,id,name,artist,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,realease_year,emotion_tag
0,1,My Way,Limp Bizkit,0.576,0.864,6,-3.981,1,0.0462,0.02000,0.000002,0.6830,0.609,97.225,272973,4,2000,NaN
1,2,Symphony (feat. Zara Larsson),Clean Bandit,0.715,0.605,0,-5.128,0,0.0428,0.23900,0.000014,0.1890,0.454,122.956,212733,4,2018,NaN
2,3,concert for aliens,Machine Gun Kelly,0.507,0.951,11,-2.999,1,0.0586,0.00032,0.000000,0.3300,0.692,95.016,160222,4,2020,NaN
3,4,Everlong,Foo Fighters,0.413,0.881,11,-5.541,0,0.0367,0.00006,0.000308,0.0805,0.364,158.066,250547,4,1997,NaN
4,5,WITHOUT YOU,The Kid LAROI,0.662,0.413,0,-7.357,1,0.0299,0.21300,0.000000,0.1340,0.467,93.005,161385,4,2020,NaN

In [ ]:
columns = ["name", "artist","realease_year", "key", "mode", "time_signature", "duration_ms"]
for col in columns:
  del test[col]
test.head()

,id,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,emotion_tag
0,1,0.576,0.864,-3.981,0.0462,0.02000,0.000002,0.6830,0.609,97.225,NaN
1,2,0.715,0.605,-5.128,0.0428,0.23900,0.000014,0.1890,0.454,122.956,NaN
2,3,0.507,0.951,-2.999,0.0586,0.00032,0.000000,0.3300,0.692,95.016,NaN
3,4,0.413,0.881,-5.541,0.0367,0.00006,0.000308,0.0805,0.364,158.066,NaN
4,5,0.662,0.413,-7.357,0.0299,0.21300,0.000000,0.1340,0.467,93.005,NaN

# Model

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB

In [ ]:
# Load your labeled and unlabeled data as pandas DataFrames
labeled_data = labelled
unlabeled_data = unlabelled

# Perform pseudo-labelling on the unlabeled data
pseudo_labels = []

# Define the Naive Bayes classifier
naive_bayes = GaussianNB()

x_labeled = labeled_data[['danceability', 'energy', 'loudness', 'speechiness', 'acousticness',
       'instrumentalness', 'valence']]
y_labeled = labeled_data['emotion_tag']

x_unlabeled = unlabeled_data[['danceability', 'energy', 'loudness', 'speechiness', 'acousticness',
       'instrumentalness', 'valence']]

# Train the Naive Bayes classifier on the labeled data
naive_bayes.fit(x_labeled, y_labeled)

# Generate pseudo-labels for the unlabeled data
pseudo_labels = naive_bayes.predict(x_unlabeled)

# Combine the labeled and pseudo-labeled data

X_combined = np.concatenate((x_labeled, x_unlabeled), axis=0)
y_combined = np.concatenate((y_labeled, torch.tensor(pseudo_labels)), axis=0)

In [ ]:
#X_train, X_test, y_train, y_test = train_test_split(X_combined, y_combined, test_size=0.2, random_state=42)

X_train = X_combined
y_train = y_combined
X_test = test[['danceability', 'energy', 'loudness', 'speechiness', 'acousticness',
       'instrumentalness', 'valence']]
y_test = test["emotion_tag"]

# Normalize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Convert data to PyTorch tensors
X_train = torch.tensor(X_train, dtype=torch.float)
y_train = torch.tensor(y_train, dtype=torch.long)
X_test = torch.tensor(X_test, dtype=torch.float)


# Define the MLP model architecture
class MLP(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(MLP, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out

# Set the hyperparameters
input_size = X_train.shape[1]
hidden_size = 64
num_classes = 4
learning_rate = 0.001
num_epochs = 10
batch_size = 32

# Create the MLP model
model = MLP(input_size, hidden_size, num_classes)

# Define the loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Training loop
for epoch in range(num_epochs):
    model.train()
    total_loss = 0.0
    total_samples = 0

    # Mini-batch training
    for i in range(0, len(X_train), batch_size):
        # Get the mini-batch data
        inputs = X_train[i:i+batch_size]
        labels = y_train[i:i+batch_size]

        # Forward pass
        outputs = model(inputs)
        loss = criterion(outputs, labels)

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # Update loss and sample count
        total_loss += loss.item() * inputs.size(0)
        total_samples += inputs.size(0)

    # Calculate average loss
    avg_loss = total_loss / total_samples

    # Print the average loss for this epoch
    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {avg_loss:.4f}")

# Evaluation
model.eval()
with torch.no_grad():
    # Predict on test set
    outputs = model(X_test)
    _, predicted = torch.max(outputs.data, 1)

    # Calculate accuracy

    #print(f"Test Accuracy: {accuracy:.4f}")

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

Epoch 1/10, Loss: 1.0453
Epoch 2/10, Loss: 0.6379
Epoch 3/10, Loss: 0.5118
Epoch 4/10, Loss: 0.4711
Epoch 5/10, Loss: 0.4546
Epoch 6/10, Loss: 0.4459
Epoch 7/10, Loss: 0.4401
Epoch 8/10, Loss: 0.4356
Epoch 9/10, Loss: 0.4319
Epoch 10/10, Loss: 0.4288

# Submission

In [ ]:
test["emotion_tag"] = predicted

In [ ]:
test["emotion_tag"]

0      2
1      2
2      2
3      0
4      3
      ..
595    0
596    0
597    2
598    2
599    0
Name: emotion_tag, Length: 600, dtype: int64

In [ ]:
id = test["id"]
emotion_tag = test["emotion_tag"]

In [ ]:
sample_submission = pd.DataFrame(list(zip(id, emotion_tag)),
               columns =['id', 'emotion_tag'])

In [ ]:
sample_submission

      id  emotion_tag
0      1            2
1      2            2
2      3            2
3      4            0
4      5            3
..   ...          ...
595  596            0
596  597            0
597  598            2
598  599            2
599  600            0

[600 rows x 2 columns]

In [ ]:
for i in range(len(sample_submission['emotion_tag'])):
  if sample_submission.iloc[i]['emotion_tag'] == 3:
    sample_submission['emotion_tag'][i] = "sad"
  elif sample_submission.iloc[i]['emotion_tag'] == 2:
    sample_submission['emotion_tag'][i] = "happy"
  elif sample_submission.iloc[i]['emotion_tag'] == 1:
    sample_submission['emotion_tag'][i] = "chill"
  elif sample_submission.iloc[i]['emotion_tag'] == 0:
    sample_submission['emotion_tag'][i] = "angry"
sample_submission

      id emotion_tag
0      1       happy
1      2       happy
2      3       happy
3      4       angry
4      5         sad
..   ...         ...
595  596       angry
596  597       angry
597  598       happy
598  599       happy
599  600       angry

[600 rows x 2 columns]

In [ ]:
from google.colab import files
sample_submission.to_csv('NBoutput.csv', index=False)
files.download('NBoutput.csv')